---
# handlers file for docker-role
- name: start docker
  systemd: name=docker state=started daemon_reload=yes

- name: restart docker
  systemd: name=docker state=restarted

- name: no mask
  systemd: name=docker enabled=yes masked=no
